version: 2.1

commands:
  install-aws-cli:
    steps:
      - run: echo instalando aws... 
      
jobs:
  install-dependencies:
    docker:
      - image: cimg/base:stable # imagen que tiene lo suyo, imagen valida de circleCi=cimg
    steps:
      - checkout:
          path: micodigo/
      - run: ls -lt micodigo/
      - install-aws-cli
      - run: 
          command: echo Uso Var en Contexto= $NOMBRE 

workflows:
  workflow1:
    jobs:
      - install-dependencies:
          context: Prueba-Contexto
